{% set version = '0.8.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: 99a508d0539390364789c5f4835b36c4a383927f0ec1648e2a4636c1cc6e490f

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect

test:
  commands:
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

about:
  home: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT
  summary: An evolution of 'reshape2'. It's designed specifically for data tidying (not general
    reshaping or aggregating) and works well with 'dplyr' data pipelines.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
