{% set version = '0.8.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tidyr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: 0b7fb3e4ee7c6c8bb9894825c7f16db967abb57aceac0609b7866fa1825c57e2

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('tidyr')"  # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

about:
  home: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT
  summary: An evolution of 'reshape2'. It's designed specifically for data tidying (not general
    reshaping or aggregating) and works well with 'dplyr' data pipelines.
  license_family: MIT

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
