{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: 8d532b9366fdd3ec9827b51830e559a49d073425007c766025f0e603964e0a9d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cli                      # [build_platform != target_platform]
    - r-glue                     # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-lifecycle                # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-vctrs                    # [build_platform != target_platform]
    - r-purrr                    # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-stringr                  # [build_platform != target_platform]
    - r-tibble                   # [build_platform != target_platform]
    - r-tidyselect               # [build_platform != target_platform]
    - r-cpp11                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11 >=0.4.0
    - r-cli >=3.4.1
    - r-dplyr >=1.0.10
    - r-glue
    - r-lifecycle >=1.0.3
    - r-magrittr
    - r-purrr >=1.0.1
    - r-rlang >=1.0.4
    - r-stringr >=1.5.0
    - r-tibble >=2.1.1
    - r-tidyselect >=1.2.0
    - r-vctrs >=0.5.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli >=3.4.1
    - r-dplyr >=1.0.10
    - r-glue
    - r-lifecycle >=1.0.3
    - r-magrittr
    - r-purrr >=1.0.1
    - r-rlang >=1.0.4
    - r-stringr >=1.5.0
    - r-tibble >=2.1.1
    - r-tidyselect >=1.2.0
    - r-vctrs >=0.5.2

test:
  commands:
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

about:
  home: https://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT
  summary: Tools to help to create tidy data, where each column is a  variable, each row is an observation, and each cell contains a single value.   'tidyr' contains tools for changing the shape (pivoting) and hierarchy (nesting and 'unnesting') of a dataset, turning deeply nested lists into rectangular data frames ('rectangling'),
    and extracting values out  of string columns. It also includes tools for working with missing values  (both implicit and explicit).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidyr
# Title: Tidy Messy Data
# Version: 1.0.0
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = "aut", email = "lionel@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Tools to help to create tidy data, where each column is a  variable, each row is an observation, and each cell contains a single value.   'tidyr' contains tools for changing the shape (pivoting) and hierarchy (nesting and 'unnesting') of a dataset, turning deeply nested lists into rectangular data frames ('rectangling'), and extracting values out  of string columns. It also includes tools for working with missing values  (both implicit and explicit).
# License: MIT + file LICENSE
# URL: https://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
# BugReports: https://github.com/tidyverse/tidyr/issues
# Depends: R (>= 3.1)
# Imports: dplyr (>= 0.8.2), ellipsis (>= 0.1.0), glue, magrittr, purrr, Rcpp, rlang, stringi, tibble (>= 2.1.1), tidyselect (>= 0.2.5), utils, vctrs (>= 0.2.0), lifecycle
# Suggests: covr, jsonlite, knitr, repurrrsive (>= 1.0.0), rmarkdown, readr, testthat (>= 2.1.0)
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-09-10 12:06:26 UTC; hadley
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-11 23:00:03 UTC
