{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: 2403dd2f4d350d1ecb449be5d61cdccf6655572a807409325f9122c716924e69

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr >=0.8.2
    - r-ellipsis >=0.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble >=2.1.1
    - r-tidyselect >=0.2.5
    - r-vctrs >=0.2.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.8.2
    - r-ellipsis >=0.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble >=2.1.1
    - r-tidyselect >=0.2.5
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

about:
  home: https://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT
  summary: Tools to help to create tidy data, where each column is a  variable, each row is an
    observation, and each cell contains a single value.   'tidyr' contains tools for
    changing the shape (pivoting) and hierarchy (nesting and 'unnesting') of a dataset,
    turning deeply nested lists into rectangular data frames ('rectangling'), and extracting
    values out  of string columns. It also includes tools for working with missing values  (both
    implicit and explicit).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidyr
# Title: Tidy Messy Data
# Version: 1.0.0
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = "aut", email = "lionel@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Tools to help to create tidy data, where each column is a  variable, each row is an observation, and each cell contains a single value.   'tidyr' contains tools for changing the shape (pivoting) and hierarchy (nesting and 'unnesting') of a dataset, turning deeply nested lists into rectangular data frames ('rectangling'), and extracting values out  of string columns. It also includes tools for working with missing values  (both implicit and explicit).
# License: MIT + file LICENSE
# URL: https://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
# BugReports: https://github.com/tidyverse/tidyr/issues
# Depends: R (>= 3.1)
# Imports: dplyr (>= 0.8.2), ellipsis (>= 0.1.0), glue, magrittr, purrr, Rcpp, rlang, stringi, tibble (>= 2.1.1), tidyselect (>= 0.2.5), utils, vctrs (>= 0.2.0), lifecycle
# Suggests: covr, jsonlite, knitr, repurrrsive (>= 1.0.0), rmarkdown, readr, testthat (>= 2.1.0)
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-09-10 12:06:26 UTC; hadley
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-11 23:00:03 UTC
