{% set version = '0.8.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyr/tidyr_{{ version }}.tar.gz
  sha256: a18f54ec35124110058ab23f7e0a3c037a8d50f0405520cf5cc5443ec022cc37

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect >=0.2.5
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.7.0
    - r-glue
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
    - r-tidyselect >=0.2.5

test:
  commands:
    - $R -e "library('tidyr')"           # [not win]
    - "\"%R%\" -e \"library('tidyr')\""  # [win]

about:
  home: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
  license: MIT
  summary: An evolution of 'reshape2'. It's designed specifically for data tidying (not general
    reshaping or aggregating) and works well with 'dplyr' data pipelines.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidyr
# Title: Easily Tidy Data with 'spread()' and 'gather()' Functions
# Version: 0.8.3
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = "aut", email = "lionel@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: An evolution of 'reshape2'. It's designed specifically for data tidying (not general reshaping or aggregating) and works well with 'dplyr' data pipelines.
# License: MIT + file LICENSE
# URL: http://tidyr.tidyverse.org, https://github.com/tidyverse/tidyr
# BugReports: https://github.com/tidyverse/tidyr/issues
# Depends: R (>= 3.1)
# Imports: dplyr (>= 0.7.0), glue, magrittr, purrr, Rcpp, rlang, stringi, tibble, tidyselect (>= 0.2.5), utils
# Suggests: covr, gapminder, knitr, rmarkdown, testthat
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-02-28 16:04:27 UTC; hadley
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-03-01 23:00:03 UTC
