travis:
  secure:
    BINSTAR_TOKEN: WiiWY5zxF4UKgi/9mHThFmcJcrAH+bZpP6O96KqZEEfi5YLHM6UJ6V8OBlJwpH5BHvZIz5qPNizLhBxVwO/Ep5J5Vybn2A0Ptd61BphIzbaQGfDKVxXql43MS0vaPt1LARQ36fnuZAVXFjKDIHWxWqSSB7InVfePTwpDTZF4QwIzu1A7E6CZ3Fzo3d0/IW7JTI3izvWdPAYYiEkaWiBpX/+H4u54p2LcBHANRffpfEj9cxB/JIy03bZzJrPbWjPGDMqRb5/gw2dbeoFK7IXrxaDL/6nrM8+NWFN3Bxunh2JIfbYV0lMdLdqr1viUIVw24HulqKPmzeyajgmPoZ9ETzWER3pLkRylujzAGHZWR6bES4BI2gUDql+leSlJftXckC2AtxbWKdfruvyVvybmH+3DDAEBgHRs1s35FOeidN/cMOLpL0wqDGKztkmIP7bMyuULifBgm7A/CAQbSghIEl0ejKLsQqymOHPo9ZcyqPucDJiMAXkTLGuQb1NAQ1UEjHAohBNV6dUp88kZd5i3/OptJx+CdKUhrqm2vtXdz/NVivI6qpeyYUexixGewMdiv5SQq+/rhdfgQdQQsCLhemgh4qqGxtmFmbghyK7wmDNwVg9uc5b2cgIH9L+ge2frMTR8WDLtTo3l0sHWoO1e24A1mcGiHtsv0tor/74/mY0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
